-- Unlock HR schema and grant SELECT access to ADMIN
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER USER HR ACCOUNT UNLOCK;

GRANT SELECT ON HR.EMPLOYEES TO ADMIN;
GRANT SELECT ON HR.DEPARTMENTS TO ADMIN;
GRANT SELECT ON HR.JOBS TO ADMIN;
GRANT SELECT ON HR.JOB_HISTORY TO ADMIN;
GRANT SELECT ON HR.LOCATIONS TO ADMIN;
GRANT SELECT ON HR.COUNTRIES TO ADMIN;
GRANT SELECT ON HR.REGIONS TO ADMIN;

EXIT;
