spring:
  application:
    name: backend
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:oracle:thin:@SERVICE_NAME_high?TNS_ADMIN=/PATH/TO/WALLET
    username: ADMIN
    password: "PASSWORD"
    oracleucp:
      initial-pool-size: 2
      min-pool-size: 2
      max-pool-size: 10
server:
  port: 8080
selectai:
  profile:
    query: GENAI_SELECT_AI
    rag: GENAI_RAG
  agents:
    team: SH_ANALYST_TEAM
